/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contractSol from './contract.sol/index.js';
export type { contractSol };
export type { Counter } from './Counter.js';
export * as factories from './factories/index.js';
export { Counter__factory } from './factories/Counter__factory.js';
export type { SupplyChainProvenance } from './contract.sol/SupplyChainProvenance.js';
export { SupplyChainProvenance__factory } from './factories/contract.sol/SupplyChainProvenance__factory.js';