/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface SupplyChainProvenanceInterface extends Interface {
    getFunction(nameOrSignature: "actorList" | "actorReceiveSign" | "actorSendSign" | "createItem" | "getItem" | "getSignature" | "itemList" | "owner" | "registerActor"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "actorRegistered" | "itemCreated" | "itemSigned"): EventFragment;

    encodeFunctionData(functionFragment: 'actorList', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'actorReceiveSign', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'actorSendSign', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'createItem', values: [string, string]): string;
encodeFunctionData(functionFragment: 'getItem', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSignature', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'itemList', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerActor', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'actorList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'actorReceiveSign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'actorSendSign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSignature', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'itemList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerActor', data: BytesLike): Result;
  }

  
    export namespace actorRegisteredEvent {
      export type InputTuple = [actorAddr: AddressLike, role: BigNumberish];
      export type OutputTuple = [actorAddr: string, role: bigint];
      export interface OutputObject {actorAddr: string, role: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace itemCreatedEvent {
      export type InputTuple = [itemId: BigNumberish, itemName: string, creatorAddr: AddressLike];
      export type OutputTuple = [itemId: bigint, itemName: string, creatorAddr: string];
      export interface OutputObject {itemId: bigint, itemName: string, creatorAddr: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace itemSignedEvent {
      export type InputTuple = [itemId: BigNumberish, signerAddr: AddressLike, role: BigNumberish, updatedStatus: BigNumberish, note: string];
      export type OutputTuple = [itemId: bigint, signerAddr: string, role: bigint, updatedStatus: bigint, note: string];
      export interface OutputObject {itemId: bigint, signerAddr: string, role: bigint, updatedStatus: bigint, note: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SupplyChainProvenance extends BaseContract {
    
    connect(runner?: ContractRunner | null): SupplyChainProvenance;
    waitForDeployment(): Promise<this>;

    interface: SupplyChainProvenanceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    actorList: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, string, boolean] & {role: bigint, actorAddress: string, exists: boolean }],
      'view'
    >
    

    
    actorReceiveSign: TypedContractMethod<
      [itemId: BigNumberish, signatureNote: string, ],
      [void],
      'nonpayable'
    >
    

    
    actorSendSign: TypedContractMethod<
      [itemId: BigNumberish, signatureNote: string, ],
      [void],
      'nonpayable'
    >
    

    
    createItem: TypedContractMethod<
      [itemName: string, metadata: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    getItem: TypedContractMethod<
      [itemId: BigNumberish, ],
      [[bigint, string, string, string, bigint] & {id: bigint, itemName: string, itemMetadata: string, itemCreator: string, status: bigint }],
      'view'
    >
    

    
    getSignature: TypedContractMethod<
      [itemId: BigNumberish, signatureIndex: BigNumberish, ],
      [[string, bigint, bigint, string] & {signerAddress: string, signerRole: bigint, signatureTimestamp: bigint, signatureNote: string }],
      'view'
    >
    

    
    itemList: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, boolean] & {itemId: bigint, itemName: string, metadata: string, creator: string, status: bigint, exists: boolean }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerActor: TypedContractMethod<
      [actorAddr: AddressLike, role: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'actorList'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, string, boolean] & {role: bigint, actorAddress: string, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'actorReceiveSign'): TypedContractMethod<
      [itemId: BigNumberish, signatureNote: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'actorSendSign'): TypedContractMethod<
      [itemId: BigNumberish, signatureNote: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createItem'): TypedContractMethod<
      [itemName: string, metadata: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getItem'): TypedContractMethod<
      [itemId: BigNumberish, ],
      [[bigint, string, string, string, bigint] & {id: bigint, itemName: string, itemMetadata: string, itemCreator: string, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getSignature'): TypedContractMethod<
      [itemId: BigNumberish, signatureIndex: BigNumberish, ],
      [[string, bigint, bigint, string] & {signerAddress: string, signerRole: bigint, signatureTimestamp: bigint, signatureNote: string }],
      'view'
    >;
getFunction(nameOrSignature: 'itemList'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, boolean] & {itemId: bigint, itemName: string, metadata: string, creator: string, status: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerActor'): TypedContractMethod<
      [actorAddr: AddressLike, role: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'actorRegistered'): TypedContractEvent<actorRegisteredEvent.InputTuple, actorRegisteredEvent.OutputTuple, actorRegisteredEvent.OutputObject>;
getEvent(key: 'itemCreated'): TypedContractEvent<itemCreatedEvent.InputTuple, itemCreatedEvent.OutputTuple, itemCreatedEvent.OutputObject>;
getEvent(key: 'itemSigned'): TypedContractEvent<itemSignedEvent.InputTuple, itemSignedEvent.OutputTuple, itemSignedEvent.OutputObject>;

    filters: {
      
      'actorRegistered(address,uint8)': TypedContractEvent<actorRegisteredEvent.InputTuple, actorRegisteredEvent.OutputTuple, actorRegisteredEvent.OutputObject>;
      actorRegistered: TypedContractEvent<actorRegisteredEvent.InputTuple, actorRegisteredEvent.OutputTuple, actorRegisteredEvent.OutputObject>;
    

      'itemCreated(uint256,string,address)': TypedContractEvent<itemCreatedEvent.InputTuple, itemCreatedEvent.OutputTuple, itemCreatedEvent.OutputObject>;
      itemCreated: TypedContractEvent<itemCreatedEvent.InputTuple, itemCreatedEvent.OutputTuple, itemCreatedEvent.OutputObject>;
    

      'itemSigned(uint256,address,uint8,uint8,string)': TypedContractEvent<itemSignedEvent.InputTuple, itemSignedEvent.OutputTuple, itemSignedEvent.OutputObject>;
      itemSigned: TypedContractEvent<itemSignedEvent.InputTuple, itemSignedEvent.OutputTuple, itemSignedEvent.OutputObject>;
    
    };
  }